version: "3"

services:
  prod-postgresdb:
    image: postgres
    container_name: prod-postgresdb
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - prod-postgresdatax:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - prod-backend-net

  prod-rabbitmq:
    image: rabbitmq:3-management
    container_name: prod-rabbitmq
    ports:
      - "15672:15672" # Management UI
      - "5672:5672"   # AMQP port
    env_file:
      - ./.env
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_running"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - prod-backend-net
    restart: unless-stopped

  backend:
    build: .
    container_name: production
    ports:
      - "8080:8080"
    env_file:
      - ./.env
    environment:
      - SPRING_CONFIG_LOCATION=/app/config/application.properties
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
    volumes:
      - ./src/main/resources/application.properties:/app/config/application.properties
    networks:
      - prod-backend-net
    depends_on:
      prod-rabbitmq:
        condition: service_healthy
      prod-postgresdb:
        condition: service_healthy
    restart: unless-stopped

networks:
  prod-backend-net:
    driver: bridge

volumes:
  prod-postgresdatax:
